service: serverless-nestjs-test

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, 'prisma-nestjs-serverless-demo'}

functions:
  user:
    handler: dist/main.handler
    events:
      - http:
          path: /users/{any+}
          method: any

plugins:
  - serverless-dotenv-plugin
  - serverless-scriptable-plugin
  - serverless-webpack
  - serverless-jetpack
  - serverless-offline

# this exclude is specific to your system if your not on the same environment as Lambda
# this is added to decrease the output size to prevent size related issues
package:
  include:
    - 'schema.prisma'

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: 'yarn build'
  webpack:
    excludeFiles: '**/*test*'
    includeModules:
      forceExclude:
        - 'aws-sdk'
    keepOutputDirectory: true
    packager: 'yarn'
  jetpack:
    collapsed:
      bail: true
    concurrency: 4
    preInclude:
      - '!**'
    trace:
      dynamic:
        bail: true
  serverless-offline:
    useChildProcesses: true
